print ('Naaminvoer')
name = input('Geef uw naam+achternaam')
print('Hallo'+name)
Adres = input('Geef uw Adres')   
Postcode = input ('Geef uw postcode')
print(Adres + Postcode)
woonplaats = input ('Geef uw woonplaats maatje')
print("----------------------------")
print(name)
print(Adres)
print (Postcode)
print (woonplaats)