print ('Naaminvoer')
name = input('Geef jouw naam')
print('Hallo'+name)
Adres = input('Geef uw Adres + Postcode')   
Postcode = input ('Geef uw postcode')
print(Adres + Postcode)
woonplaats = input ('Geef uw woonplaats vieze flikker')
print(woonplaats)
